# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-10-25 12:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_author_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.DateField(default=datetime.datetime(2020, 10, 25, 12, 2, 7, 608292)),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(default='匿名', max_length=30),
        ),
    ]
