# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-10-27 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20201027_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='picture',
            field=models.ImageField(null=True, upload_to='static/upload/usrimg'),
        ),
    ]
