# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-10-27 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_author_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='picture',
            field=models.ImageField(null=True, upload_to='static/upload/usrimg', verbose_name='用户图像'),
        ),
    ]
