# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-10-28 04:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_wife'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wife',
            options={'verbose_name': '女士', 'verbose_name_plural': '女士'},
        ),
        migrations.AlterField(
            model_name='wife',
            name='auth',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.Author', verbose_name='先生'),
        ),
        migrations.AlterField(
            model_name='wife',
            name='name',
            field=models.CharField(max_length=30, verbose_name='姓名'),
        ),
        migrations.AlterModelTable(
            name='wife',
            table='wife',
        ),
    ]
