# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-10-28 09:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_auto_20201028_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publ',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.Publisher'),
        ),
    ]
