# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-10-28 12:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_auto_20201028_2029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publisher',
            new_name='publisher11',
        ),
    ]
