# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-10-28 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_auto_20201028_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='publisher',
            field=models.ManyToManyField(to='index.Publisher'),
        ),
    ]
