# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2021-06-16 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0018_auto_20210616_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(to='index.Author', verbose_name='作者'),
        ),
    ]
