# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2021-03-30 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20201028_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodstype',
            name='picture',
            field=models.ImageField(upload_to='static/upload/goodstype', verbose_name='类型图片'),
        ),
    ]
